version: "3"
services:
    nodejs:
        container_name: nodejs_APP_NAME
        build:
            context: ./build/nodejs_APP_NAME
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - nodejs-network

networks:
    nodejs-network:
        driver: bridge
